# Generated by Django 4.1.7 on 2023-04-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DRFPost',
        ),
    ]
